var baseCfg = {
    projName : "game",
    resPath : "cfg/res.js",
    modluesPathMap : {
        "game" : "./",
        "cocos2d-html5" : "../node_modules/cocos2d-html5/",
        "ccmenu" : "../node_modules/ccmenu/",
        "cctouch" : "../node_modules/cctouch/",
        "ccactions" : "../node_modules/ccactions/",
        "cclabel" : "../node_modules/cclabel/",
        "ccchipmunk" : "../node_modules/ccchipmunk/",
        "ccphysics" : "../node_modules/ccphysics/",
        "ccshapenode" : "../node_modules/ccshapenode/",
        "ccbox2d" : "../node_modules/ccbox2d/",
        "cocostudio" : "../node_modules/cocostudio/",
        "ccgui" : "../node_modules/ccgui/",
        "cccliping" : "../node_modules/cccliping/",
        "ccrendertexture" : "../node_modules/ccrendertexture/",
        "ccprogress" : "../node_modules/ccprogress/",
        "cctextinput" : "../node_modules/cctextinput/",
        "cctilemap" : "../node_modules/cctilemap/",
        "cccompress" : "../node_modules/cccompress/",
        "ccaudio" : "../node_modules/ccaudio/",
        "ccparticle" : "../node_modules/ccparticle/",
        "ccaccelerometer" : "node_modules/ccaccelerometer/",
        "ccactions3d" : "node_modules/ccactions3d/",
        "cckazmath" : "../node_modules/cckazmath/",
        "ccshaders" : "../node_modules/ccshaders/",
        "cceffects" : "../node_modules/cceffects/",
        "cckeyboard" : "node_modules/cckeyboard/",
        "ccmotionstreak" : "node_modules/ccmotionstreak/",
        "ccparallax" : "node_modules/ccparallax/",
        "cctransitions" : "node_modules/cctransitions/",
        "cocosbuilder" : "node_modules/cocosbuilder/",
        "cceditbox" : "node_modules/cceditbox/",
        "ccpluginx" : "node_modules/ccpluginx/"
    },
    baseJsList : [
        "../node_modules/cocos2d-html5/cfg/jsRes.js",
        "../node_modules/cocos2d-html5/cfg/resCfg.js",
        "../node_modules/cocos2d-html5/lib/platform/CCClass.js",
        "../node_modules/cocos2d-html5/lib/cocoa/CCGeometry.js",
        "../node_modules/cocos2d-html5/lib/platform/Sys.js",
        "../node_modules/cocos2d-html5/lib/platform/CCConfig.js",
        "../node_modules/cocos2d-html5/lib/platform/miniFramework.js",
        "../node_modules/cocos2d-html5/lib/platform/CCCommon.js",
        "../node_modules/cocos2d-html5/lib/platform/CCMacro.js",
        "../node_modules/cocos2d-html5/lib/platform/CCFileUtils.js",
        "../node_modules/cocos2d-html5/lib/platform/CCTypes.js",
        "../node_modules/cocos2d-html5/lib/platform/CCEGLView.js",
        "../node_modules/cocos2d-html5/lib/platform/CCScreen.js",
        "../node_modules/cocos2d-html5/lib/platform/CCVisibleRect.js",
        "../node_modules/cocos2d-html5/lib/cocoa/CCNS.js",
        "../node_modules/cocos2d-html5/lib/cocoa/CCAffineTransform.js",
        "../node_modules/cocos2d-html5/lib/support/CCPointExtension.js",
        "../node_modules/cocos2d-html5/lib/support/CCVertex.js",
        "../node_modules/cocos2d-html5/lib/support/TransformUtils.js",
        "../node_modules/cocos2d-html5/lib/base_nodes/CCNode.js",
        "../node_modules/cocos2d-html5/lib/base_nodes/CCAtlasNode.js",
        "../node_modules/cocos2d-html5/lib/textures/CCTexture2D.js",
        "../node_modules/cocos2d-html5/lib/textures/CCTextureCache.js",
        "../node_modules/cocos2d-html5/lib/textures/CCTextureAtlas.js",
        "../node_modules/cocos2d-html5/lib/scenes_nodes/CCScene.js",
        "../node_modules/cocos2d-html5/lib/layers_nodes/CCLayer.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCSprite.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCAnimation.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCAnimationCache.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCSpriteFrame.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCSpriteFrameCache.js",
        "../node_modules/cocos2d-html5/lib/sprite_nodes/CCSpriteBatchNode.js",
        "../node_modules/cocos2d-html5/lib/CCConfiguration.js",
        "../node_modules/cocos2d-html5/lib/CCDirector.js",
        "../node_modules/cocos2d-html5/lib/CCCamera.js",
        "../node_modules/cocos2d-html5/lib/CCScheduler.js",
        "../node_modules/cocos2d-html5/lib/CCLoader.js",
        "../node_modules/cocos2d-html5/lib/CCDrawingPrimitives.js",
        "../node_modules/cocos2d-html5/lib/platform/CCApplication.js",
        "../node_modules/cocos2d-html5/lib/platform/CCSAXParser.js",
        "../node_modules/cocos2d-html5/lib/platform/AppControl.js",
        "../node_modules/cocos2d-html5/lib/labelTTF/CCLabelTTF.js",
        "../node_modules/cocos2d-html5/lib/CCActionManager.js",
        "../node_modules/cctouch/cfg/jsRes.js",
        "../node_modules/cctouch/cfg/resCfg.js",
        "../node_modules/cctouch/lib/CCTouchDelegateProtocol.js",
        "../node_modules/cctouch/lib/CCTouchHandler.js",
        "../node_modules/cctouch/lib/CCTouchDispatcher.js",
        "../node_modules/cctouch/lib/CCMouseDispatcher.js",
        "../node_modules/ccactions/cfg/jsRes.js",
        "../node_modules/ccactions/cfg/resCfg.js",
        "../node_modules/ccactions/lib/CCAction.js",
        "../node_modules/ccactions/lib/CCActionInterval.js",
        "../node_modules/ccactions/lib/CCActionInstant.js",
        "../node_modules/ccactions/lib/CCActionCamera.js",
        "../node_modules/ccactions/lib/CCActionEase.js",
        "../node_modules/ccactions/lib/CCActionCatmullRom.js",
        "../node_modules/ccactions/lib/CCActionTween.js",
        "../node_modules/ccmenu/cfg/jsRes.js",
        "../node_modules/ccmenu/cfg/resCfg.js",
        "../node_modules/ccmenu/lib/CCMenuItem.js",
        "../node_modules/ccmenu/lib/CCMenu.js",
        "../node_modules/cclabel/cfg/jsRes.js",
        "../node_modules/cclabel/cfg/resCfg.js",
        "../node_modules/cclabel/lib/CCLabelAtlas.js",
        "../node_modules/cclabel/lib/CCLabelBMFont.js",
        "../node_modules/ccchipmunk/cfg/jsRes.js",
        "../node_modules/ccchipmunk/cfg/resCfg.js",
        "../node_modules/ccchipmunk/lib/chipmunk.js",
        "../node_modules/ccshapenode/cfg/jsRes.js",
        "../node_modules/ccshapenode/cfg/resCfg.js",
        "../node_modules/ccshapenode/lib/CCDrawNode.js",
        "../node_modules/ccbox2d/cfg/jsRes.js",
        "../node_modules/ccbox2d/cfg/resCfg.js",
        "../node_modules/ccbox2d/lib/box2d.js",
        "../node_modules/ccphysics/cfg/jsRes.js",
        "../node_modules/ccphysics/cfg/resCfg.js",
        "../node_modules/ccphysics/lib/CCPhysicsSprite.js",
        "../node_modules/ccphysics/lib/CCPhysicsDebugNode.js",
        "../node_modules/cccliping/cfg/jsRes.js",
        "../node_modules/cccliping/cfg/resCfg.js",
        "../node_modules/cccliping/lib/CCClippingNode.js",
        "../node_modules/ccrendertexture/cfg/jsRes.js",
        "../node_modules/ccrendertexture/cfg/resCfg.js",
        "../node_modules/ccrendertexture/lib/CCRenderTexture.js",
        "../node_modules/ccprogress/cfg/jsRes.js",
        "../node_modules/ccprogress/cfg/resCfg.js",
        "../node_modules/ccprogress/lib/CCProgressTimer.js",
        "../node_modules/ccprogress/lib/CCActionProgressTimer.js",
        "../node_modules/ccgui/cfg/jsRes.js",
        "../node_modules/ccgui/cfg/resCfg.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControl.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlButton.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlUtils.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCInvocation.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCScale9Sprite.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCMenuPassive.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlSaturationBrightnessPicker.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlHuePicker.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlColourPicker.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlSlider.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlSwitch.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlStepper.js",
        "../node_modules/ccgui/lib/CCControlExtension/CCControlPotentiometer.js",
        "../node_modules/ccgui/lib/CCScrollView/CCScrollView.js",
        "../node_modules/ccgui/lib/CCScrollView/CCSorting.js",
        "../node_modules/ccgui/lib/CCScrollView/CCTableView.js",
        "../node_modules/cctextinput/cfg/jsRes.js",
        "../node_modules/cctextinput/cfg/resCfg.js",
        "../node_modules/cctextinput/lib/CCIMEDispatcher.js",
        "../node_modules/cctextinput/lib/CCTextFieldTTF.js",
        "../node_modules/cccompress/cfg/jsRes.js",
        "../node_modules/cccompress/cfg/resCfg.js",
        "../node_modules/cccompress/lib/ZipUtils.js",
        "../node_modules/cccompress/lib/base64.js",
        "../node_modules/cccompress/lib/gzip.js",
        "../node_modules/cccompress/lib/zlib.min.js",
        "../node_modules/cctilemap/cfg/jsRes.js",
        "../node_modules/cctilemap/cfg/resCfg.js",
        "../node_modules/cctilemap/lib/CCTGAlib.js",
        "../node_modules/cctilemap/lib/CCTMXTiledMap.js",
        "../node_modules/cctilemap/lib/CCTMXXMLParser.js",
        "../node_modules/cctilemap/lib/CCTMXObjectGroup.js",
        "../node_modules/cctilemap/lib/CCTMXLayer.js",
        "../node_modules/ccaudio/cfg/jsRes.js",
        "../node_modules/ccaudio/cfg/resCfg.js",
        "../node_modules/ccaudio/lib/SimpleAudioEngine.js",
        "../node_modules/ccparticle/cfg/jsRes.js",
        "../node_modules/ccparticle/cfg/resCfg.js",
        "../node_modules/ccparticle/lib/CCFormatHelper.js",
        "../node_modules/ccparticle/lib/CCPNGReader.js",
        "../node_modules/ccparticle/lib/CCTIFFReader.js",
        "../node_modules/ccparticle/lib/CCParticleSystem.js",
        "../node_modules/ccparticle/lib/CCParticleExamples.js",
        "../node_modules/ccparticle/lib/CCParticleBatchNode.js",
        "../node_modules/cocostudio/cfg/jsRes.js",
        "../node_modules/cocostudio/cfg/resCfg.js",
        "../node_modules/cocostudio/lib/Components/CCComponent.js",
        "../node_modules/cocostudio/lib/Components/CCComponentContainer.js",
        "../node_modules/cocostudio/lib/CocoStudio.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCArmatureDefine.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCDataReaderHelper.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCSpriteFrameCacheHelper.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCTransformHelp.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCTweenFunction.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCUtilMath.js",
        "../node_modules/cocostudio/lib/Armature/utils/CCArmatureDataManager.js",
        "../node_modules/cocostudio/lib/Armature/datas/CCDatas.js",
        "../node_modules/cocostudio/lib/Armature/display/CCDecorativeDisplay.js",
        "../node_modules/cocostudio/lib/Armature/display/CCDisplayFactory.js",
        "../node_modules/cocostudio/lib/Armature/display/CCDisplayManager.js",
        "../node_modules/cocostudio/lib/Armature/display/CCSkin.js",
        "../node_modules/cocostudio/lib/Armature/animation/CCProcessBase.js",
        "../node_modules/cocostudio/lib/Armature/animation/CCArmatureAnimation.js",
        "../node_modules/cocostudio/lib/Armature/animation/CCTween.js",
        "../node_modules/cocostudio/lib/Armature/physics/CCColliderDetector.js",
        "../node_modules/cocostudio/lib/Armature/CCArmature.js",
        "../node_modules/cocostudio/lib/Armature/CCBone.js",
        "../node_modules/cocostudio/lib/Action/CCActionFrame.js",
        "../node_modules/cocostudio/lib/Action/CCActionManager.js",
        "../node_modules/cocostudio/lib/Action/CCActionNode.js",
        "../node_modules/cocostudio/lib/Action/CCActionObject.js",
        "../node_modules/cocostudio/lib/Components/CCComAttribute.js",
        "../node_modules/cocostudio/lib/Components/CCComAudio.js",
        "../node_modules/cocostudio/lib/Components/CCComController.js",
        "../node_modules/cocostudio/lib/Components/CCComRender.js",
        "../node_modules/cocostudio/lib/GUI/BaseClasses/UIWidget.js",
        "../node_modules/cocostudio/lib/GUI/Layouts/UILayout.js",
        "../node_modules/cocostudio/lib/GUI/Layouts/UILayoutParameter.js",
        "../node_modules/cocostudio/lib/GUI/Layouts/UILayoutDefine.js",
        "../node_modules/cocostudio/lib/GUI/System/CocosGUI.js",
        "../node_modules/cocostudio/lib/GUI/System/UIHelper.js",
        "../node_modules/cocostudio/lib/GUI/System/UILayer.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UIButton.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UICheckBox.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UIImageView.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UILabel.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UILabelAtlas.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UILabelBMFont.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UILoadingBar.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UISlider.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UISwitch.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/UITextField.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/Compatible/CompatibleClasses.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/ScrollWidget/UIScrollView.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/ScrollWidget/UIListView.js",
        "../node_modules/cocostudio/lib/GUI/UIWidgets/ScrollWidget/UIPageView.js",
        "../node_modules/cocostudio/lib/Reader/GUIReader.js",
        "../node_modules/cocostudio/lib/Reader/SceneReader.js",
        "../node_modules/cocostudio/lib/Trigger/ObjectFactory.js",
        "../node_modules/cocostudio/lib/Trigger/TriggerBase.js",
        "../node_modules/cocostudio/lib/Trigger/TriggerMng.js",
        "../node_modules/cocostudio/lib/Trigger/TriggerObj.js",
        "node_modules/ccaccelerometer/cfg/jsRes.js",
        "node_modules/ccaccelerometer/cfg/resCfg.js",
        "node_modules/ccaccelerometer/lib/CCAccelerometer.js",
        "../node_modules/cckazmath/cfg/jsRes.js",
        "../node_modules/cckazmath/cfg/resCfg.js",
        "../node_modules/cckazmath/lib/utility.js",
        "../node_modules/cckazmath/lib/vec2.js",
        "../node_modules/cckazmath/lib/vec3.js",
        "../node_modules/cckazmath/lib/vec4.js",
        "../node_modules/cckazmath/lib/ray2.js",
        "../node_modules/cckazmath/lib/mat3.js",
        "../node_modules/cckazmath/lib/mat4.js",
        "../node_modules/cckazmath/lib/plane.js",
        "../node_modules/cckazmath/lib/quaternion.js",
        "../node_modules/cckazmath/lib/aabb.js",
        "../node_modules/cckazmath/lib/GL/mat4stack.js",
        "../node_modules/cckazmath/lib/GL/matrix.js",
        "../node_modules/ccshaders/cfg/jsRes.js",
        "../node_modules/ccshaders/cfg/resCfg.js",
        "../node_modules/ccshaders/lib/CCShaders.js",
        "../node_modules/ccshaders/lib/CCShaderCache.js",
        "../node_modules/ccshaders/lib/CCGLProgram.js",
        "../node_modules/ccshaders/lib/CCGLStateCache.js",
        "../node_modules/cceffects/cfg/jsRes.js",
        "../node_modules/cceffects/cfg/resCfg.js",
        "../node_modules/cceffects/lib/CCGrid.js",
        "../node_modules/cceffects/lib/CCGrabber.js",
        "node_modules/ccactions3d/cfg/jsRes.js",
        "node_modules/ccactions3d/cfg/resCfg.js",
        "node_modules/ccactions3d/lib/CCActionGrid.js",
        "node_modules/ccactions3d/lib/CCActionGrid3D.js",
        "node_modules/ccactions3d/lib/CCActionTiledGrid.js",
        "node_modules/ccactions3d/lib/CCActionPageTurn3D.js",
        "node_modules/cckeyboard/cfg/jsRes.js",
        "node_modules/cckeyboard/cfg/resCfg.js",
        "node_modules/cckeyboard/lib/CCKeyboardDelegate.js",
        "node_modules/cckeyboard/lib/CCKeyboardDispatcher.js",
        "node_modules/ccmotionstreak/cfg/jsRes.js",
        "node_modules/ccmotionstreak/cfg/resCfg.js",
        "node_modules/ccmotionstreak/lib/CCMotionStreak.js",
        "node_modules/ccparallax/cfg/jsRes.js",
        "node_modules/ccparallax/cfg/resCfg.js",
        "node_modules/ccparallax/lib/CCParallaxNode.js",
        "node_modules/cctransitions/cfg/jsRes.js",
        "node_modules/cctransitions/cfg/resCfg.js",
        "node_modules/cctransitions/lib/CCTransition.js",
        "node_modules/cctransitions/lib/CCTransitionProgress.js",
        "node_modules/cctransitions/lib/CCTransitionPageTurn.js",
        "node_modules/cocosbuilder/cfg/jsRes.js",
        "node_modules/cocosbuilder/cfg/resCfg.js",
        "node_modules/cocosbuilder/lib/CCNodeLoader.js",
        "node_modules/cocosbuilder/lib/CCBReaderUtil.js",
        "node_modules/cocosbuilder/lib/CCControlLoader.js",
        "node_modules/cocosbuilder/lib/CCSpriteLoader.js",
        "node_modules/cocosbuilder/lib/CCNodeLoaderLibrary.js",
        "node_modules/cocosbuilder/lib/CCBReader.js",
        "node_modules/cocosbuilder/lib/CCBValue.js",
        "node_modules/cocosbuilder/lib/CCBKeyframe.js",
        "node_modules/cocosbuilder/lib/CCBSequence.js",
        "node_modules/cocosbuilder/lib/CCBRelativePositioning.js",
        "node_modules/cocosbuilder/lib/CCBAnimationManager.js",
        "node_modules/cceditbox/cfg/jsRes.js",
        "node_modules/cceditbox/cfg/resCfg.js",
        "node_modules/cceditbox/lib/CCdomNode.js",
        "node_modules/cceditbox/lib/CCEditBox.js",
        "node_modules/ccpluginx/cfg/jsRes.js",
        "node_modules/ccpluginx/cfg/resCfg.js",
        "node_modules/ccpluginx/lib/protocols/Config.js",
        "node_modules/ccpluginx/lib/protocols/PluginUtils.js",
        "node_modules/ccpluginx/lib/protocols/PluginProtocol.js",
        "node_modules/ccpluginx/lib/protocols/ProtocolSocial.js",
        "node_modules/ccpluginx/lib/protocols/PluginFactory.js",
        "node_modules/ccpluginx/lib/protocols/PluginManager.js",
        "node_modules/ccpluginx/lib/plugins/SocialWeibo.js",
        "node_modules/ccpluginx/lib/plugins/SocialQQWeibo.js",
        "node_modules/ccpluginx/lib/plugins/SocialQzone.js",
        "node_modules/ccpluginx/lib/plugins/SocialTwitter.js",
        "node_modules/ccpluginx/lib/plugins/SocialFacebook.js",
        "cfg/jsRes.js",
        "cfg/resCfg.js"
    ]
};